### ISSUE TITLE
Distance not defined in snapshot!

### ISSUE THREAD

**Issue by cloudbreakstudios** [DarshanGowda0/GeoFlutterFire#148]
Documentation states "The within function returns a Stream of the list of DocumentSnapshot data, plus some useful metadata like distance from the centerpoint.".

However there doesn't appear to contain this distance!

```
    stream = geoflutterfire
        .collection(collectionRef: _collectionsReference)
        .within(
            center: _center,
            radius: _searchRadius,
            field: 'position',
            strictMode: true);

    stream.listen((List<DocumentSnapshot> documentList) {
      log('Document -> ${documentList[0].data()}');
      _updateList(documentList);
    });

    void _updateList(List<DocumentSnapshot> documentList) {
        print('Updating results list..');
        _listings = [];
        documentList.forEach((DocumentSnapshot document) {
            log('Doc id ${document.id}');
            final doc = document;
            final data = doc.data();
            print('doc with id ${doc.id} distance ${data['distance']}');
            FireStoreListing listing = new FireStoreListing.fromData(document.data());
            _listings.add(listing);
        });
        print('Results Count! ${_listings.length}');
        setState(() {});
    }
```

My output..

[log] Document -> {dateTime: 11-Mar-2021 13:24, userFirstName: Rob, userItemName: 1111, userEmail: r@a.com, position: {geohash: <<my_location_hash>>, geopoint: Instance of 'GeoPoint'}, totalCost: 25.00,}
[log] Doc id 2021-03-11 13:24:15.654029

Am I doing something wrong or has this property been removed from the returning dataset?

**Comment by awaik** [comment]
Hi @cloudbreakstudios 
I think this is connected with https://github.com/DarshanGowda0/GeoFlutterFire/pull/88
Should be fixed this weekend

**Comment by awaik** [comment]
What version of the package do you use?
Can you please post results `flutter pub deps -- --style=compact`

I can see that new version returns `DistanceDocSnapshot`
```
class DistanceDocSnapshot {
  final DocumentSnapshot documentSnapshot;
  double distance;

  DistanceDocSnapshot(this.documentSnapshot, this.distance);
}
```

**Comment by ericel** [comment]
This still doesn't work with  geoflutterfire: ^3.0.0-nullsafety.2
